version: '3.8'

services:
  backend:
    build: ./api
    container_name: chefhub_api
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
    environment:
      - TZ=America/Argentina/Buenos_Aires

  frontend:
    build: ./chefhub
    container_name: chefhub_frontend
    restart: always
    ports:
      - "3000:5173"
    depends_on:
      - backend
