version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: chefhub_api
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
    environment:
      - TZ=America/Argentina/Buenos_Aires

  frontend:
    build:
      context: ./chefhub
      dockerfile: Dockerfile
    container_name: chefhub_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./chefhub:/app
    working_dir: /app