version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chefhub-dev
    container_name: chefhub-docker
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:/q9Xb5KrF6FChL0O/lbW5Al6k+JkgUNrYZvFcmCBemI=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
